### ISSUE TITLE
Support for fluentd 1.15?

### ISSUE THREAD

**Issue by sschroed99** [fluent/fluent-plugin-rewrite-tag-filter#117]
Looking to see if there is support for this plugin in fluentd 1.15.  I am attempting to make a new custom fluentd image to upgrade fluentd, but getting the below when attempting to install the plugin.  I have tried with fluetnd 1.15.1 and 1.15.2.

```
Step 3/20 : RUN fluent-gem install fluent-plugin-rewrite-tag-filter
 ---> Running in 282186c8ede6
#<Thread:0x00007f4d923409b8 /usr/local/lib/ruby/3.1.0/rubygems/request_set.rb:167 run> terminated with exception (report_on_exception is true):
/usr/local/lib/ruby/3.1.0/rubygems.rb:7[83](https://gitlab.verizon.com/aether/fluentd_docker/-/jobs/21893341#L83):in `initialize': No such file or directory @ rb_sysopen - /home/fluent/.local/share/gem/ruby/3.1.0/cache/fluent-plugin-rewrite-tag-filter-2.4.0.gem (Errno::ENOENT)
	from /usr/local/lib/ruby/3.1.0/rubygems.rb:783:in `open'
	from /usr/local/lib/ruby/3.1.0/rubygems.rb:783:in `open_file'
	from /usr/local/lib/ruby/3.1.0/rubygems.rb:774:in `write_binary'
	from /usr/local/lib/ruby/3.1.0/rubygems/remote_fetcher.rb:292:in `cache_update_path'
	from /usr/local/lib/ruby/3.1.0/rubygems/remote_fetcher.rb:146:in `download'
	from /usr/local/lib/ruby/3.1.0/rubygems/source.rb:215:in `download'
	from /usr/local/lib/ruby/3.1.0/rubygems/resolver/specification.rb:112:in `download'
	from /usr/local/lib/ruby/3.1.0/rubygems/request_set.rb:173:in `block (2 levels) in install'
#<Thread:0x00007f4d[92](https://gitlab.verizon.com/aether/fluentd_docker/-/jobs/21893341#L92)3410c0 /usr/local/lib/ruby/3.1.0/rubygems/request_set.rb:167 run> terminated with exception (report_on_exception is true):
/usr/local/lib/ruby/3.1.0/rubygems.rb:783:in `initialize': No such file or directory @ rb_sysopen - /home/fluent/.local/share/gem/ruby/3.1.0/cache/fluent-config-regexp-type-1.0.0.gem (Errno::ENOENT)
	from /usr/local/lib/ruby/3.1.0/rubygems.rb:783:in `open'
	from /usr/local/lib/ruby/3.1.0/rubygems.rb:783:in `open_file'
	from /usr/local/lib/ruby/3.1.0/rubygems.rb:774:in `write_binary'
	from /usr/local/lib/ruby/3.1.0/rubygems/remote_fetcher.rb:292:in `cache_update_path'
	from /usr/local/lib/ruby/3.1.0/rubygems/remote_fetcher.rb:146:in `download'
	from /usr/local/lib/ruby/3.1.0/rubygems/source.rb:215:in `download'
	from /usr/local/lib/ruby/3.1.0/rubygems/resolver/specification.rb:112:in `download'
	from /usr/local/lib/ruby/3.1.0/rubygems/request_set.rb:173:in `block (2 levels) in install'
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory @ rb_sysopen - /home/fluent/.local/share/gem/ruby/3.1.0/cache/fluent-config-regexp-type-1.0.0.gem
The command '/bin/sh -c fluent-gem install fluent-plugin-rewrite-tag-filter' returned a non-zero code: 1
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: exit status 1
```

**Comment by sschroed99** [comment]
Turned out to be user error;)
